--hunter
--ravager
--mangonel
--skeeter
--bb
--volcano
--swatter
--geothermal
--stormcloud
--catapult
--alpha
return {
--hunter
  ["hunterflash"] = {
    usedefaultexplosions = false,
    groundflash = {
      circlealpha        = 1,
      circlegrowth       = 0,
      flashalpha         = 0.9,
      flashsize          = 10,
      ttl                = 4,
      color = {
        [1]  = 1,
        [2]  = 0.95,
        [3]  = 0.4,
      },
    },
  spark = {
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      unit               = 1,
	  water              = true,
      properties = {
        airdrag            = 0.97,
        colormap           = [[1 1 0.4 0.01   1 0.8 0.35 0.01   1 0.5 0.2 0.01   0 0 0 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 40,
        emitvector         = [[dir]],
        gravity            = [[0, -0.2, 0]],
        numparticles       = 5,
        particlelife       = 8,
        particlelifespread = 0,
        particlesize       = 8,
        particlesizespread = 0,
        particlespeed      = 3,
        particlespeedspread = 4,
        pos                = [[0, 1, 0]],
        sizegrowth         = 0,
        sizemod            = 1.0,
        texture            = [[simplespark]],
      },
    },
	 mainhit = {
      air                = true,
      class              = [[heatcloud]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        heat               = 4, --8
        heatfalloff        = 1,
        maxheat            = 4, --8
        pos                = [[0, 1, 0]],
        size               = 5.5, 
        sizegrowth         = 1, 
        speed              = [[0, 0.8, 0]],
        texture            = [[heatcloud]],
      },
	},
   },
   --ravager
	["ravagerflash"] = {
	usedefaultexplosions = false,
    groundflash = {
      circlealpha        = 1,
      circlegrowth       = 1,
      flashalpha         = 0.9,
      flashsize          = 13.5,
      ttl                = 6,
      color = {
        [1]  = 1,
        [2]  = 0.5,
        [3]  = 0.5,
      },
    },
	 mainhit = {
      air                = true,
      class              = [[heatcloud]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        heat               = 8, --8
        heatfalloff        = 1,
        maxheat            = 8, --8
        pos                = [[0, 1, 0]],
        size               = 12, 
        sizegrowth         = 1, 
        speed              = [[0, 1, 0]],
        texture            = [[heatcloud]],
      },
	},
	dirt = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      properties = {
        airdrag            = 0.95,
        colormap           = [[0.04 0.03 0.02 0.05  0.4 0.3 0.2 0.5  0.04 0.03 0.02 0.05]],
        directional        = false,
        emitrot            = 85,
        emitrotspread      = 5,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.1, 0]],
        numparticles       = 15,
        particlelife       = 15,
        particlelifespread = 4,
        particlesize       = 4,
        particlesizespread = 4,
        particlespeed      = 3,
        particlespeedspread = 1,
        pos                = [[0, 0, 0]],
        sizegrowth         = 4,
        sizemod            = 0.75,
        texture            = [[dirt]],
    },
	},
	speckdirt = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      properties = {
        airdrag            = 0.95,
        colormap           = [[0.02 0.015 0.01 0.075  0.2 0.15 0.1 0.75  0.02 0.015 0.01 0.075]],
        directional        = false,
        emitrot            = 25,
        emitrotspread      = 5,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.1, 0]],
        numparticles       = 3,
        particlelife       = 24,
        particlelifespread = 4.5,
        particlesize       = 4.25,
        particlesizespread = 3.1,
        particlespeed      = 3,
        particlespeedspread = 1,
        pos                = [[0, 0, 0]],
        sizegrowth         = 4,
        sizemod            = 0.75,
        texture            = [[randdots]],
    },
  },
   },
   ["mangonelflash"] = {
    groundflash = {
      circlealpha        = 1,
      circlegrowth       = 3.5,
      flashalpha         = 0.9,
      flashsize          = 18,
      ttl                = 10,
      color = {
        [1]  = 1,
        [2]  = 0.8,
        [3]  = 0.4,
      },
    },
	 mainhit = {
      air                = true,
      class              = [[heatcloud]],
      count              = 1,
      ground             = true,
      water              = true,
	  underwater         = true,
      properties = {
        heat               = 16, --8
        heatfalloff        = 1,
        maxheat            = 16, --8
        pos                = [[0, 1, 0]],
        size               = 18, 
        sizegrowth         = 1.5, 
        speed              = [[0, 1.5, 0]],
        texture            = [[heatcloud]],
      },
	},
	dirt = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      properties = {
        airdrag            = 0.95,
        colormap           = [[0.04 0.03 0.02 0.05  0.4 0.3 0.2 0.5  0.04 0.03 0.02 0.05]],
        directional        = false,
        emitrot            = 85,
        emitrotspread      = 5,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.1, 0]],
        numparticles       = 18,
        particlelife       = 16,
        particlelifespread = 4.5,
        particlesize       = 6,
        particlesizespread = 4.5,
        particlespeed      = 3.5,
        particlespeedspread = 1.5,
        pos                = [[0, 0, 0]],
        sizegrowth         = 6,
        sizemod            = 0.75,
        texture            = [[dirt]],
    },
	},
	speckdirt = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      properties = {
        airdrag            = 0.95,
        colormap           = [[0.02 0.015 0.01 0.075  0.2 0.15 0.1 0.75  0.02 0.015 0.01 0.075]],
        directional        = false,
        emitrot            = 25,
        emitrotspread      = 5,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.1, 0]],
        numparticles       = 4,
        particlelife       = 30,
        particlelifespread = 6,
        particlesize       = 5,
        particlesizespread = 3.5,
        particlespeed      = 3.5,
        particlespeedspread = 1.25,
        pos                = [[0, 0, 0]],
        sizegrowth         = 5,
        sizemod            = 0.75,
        texture            = [[randdots]],
    },
  },	
   },
--skeeter
  ["skeeterflash"] = {
    usedefaultexplosions = false,
    groundflash = {
      circlealpha        = 1,
      circlegrowth       = 0,
      flashalpha         = 0.9,
      flashsize          = 6,
      ttl                = 4,
      color = {
        [1]  = 1,
        [2]  = 0.95,
        [3]  = 0.4,
      },
    },
	 mainhit = {
      air                = true,
      class              = [[heatcloud]],
      count              = 1,
      ground             = true,
      water              = true,
	  underwater         = true,
      properties = {
        heat               = 4,
        heatfalloff        = 1,
        maxheat            = 4,
        pos                = [[0, 1, 0]],
        size               = 3, 
        sizegrowth         = 1, 
        speed              = [[0, 0.8, 0]],
        texture            = [[heatcloud]],
      },
	},
   },
   --bb
   ["bbflash"] = {
    groundflash = {
      circlealpha        = 1,
      circlegrowth       = 1.5,
      flashalpha         = 0.9,
      flashsize          = 90,
      ttl                = 36,
      color = {
        [1]  = 1,
        [2]  = 0.95,
        [3]  = 0.4,
      },
    },
	 mainhit = {
      air                = true,
      class              = [[heatcloud]],
      count              = 1,
      ground             = true,
      water              = true,
	  underwater         = true,
      properties = {
        heat               = 38, 
        heatfalloff        = 1,
        maxheat            = 38, 
        pos                = [[0, 1, 0]],
        size               = 54, 
        sizegrowth         = 2.5, 
        speed              = [[0, 1.5, 0]],
        texture            = [[heatcloud]],
      },
	},
	dirt = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      properties = {
        airdrag            = 0.95,
        colormap           = [[0.04 0.03 0.02 0.05  0.4 0.3 0.2 0.5  0.04 0.03 0.02 0.05]],
        directional        = false,
        emitrot            = 85,
        emitrotspread      = 15,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.1, 0]],
        numparticles       = 48,
        particlelife       = 30,
        particlelifespread = 6,
        particlesize       = 18,
        particlesizespread = 7,
        particlespeed      = 6,
        particlespeedspread = 3,
        pos                = [[0, 0, 0]],
        sizegrowth         = 6,
        sizemod            = 0.75,
        texture            = [[dirt]],
    },
	},
	},
	--volcano1
   ["volcanoflash1"] = {
    groundflash = {
      circlealpha        = 1,
      circlegrowth       = 1.5,
      flashalpha         = 0.9,
      flashsize          = 100,
      ttl                = 38,
      color = {
        [1]  = 0.8,
        [2]  = 0.65,
        [3]  = 0.4,
      },
    },
	 mainhit = {
      air                = true,
      class              = [[heatcloud]],
      count              = 1,
      ground             = true,
      water              = true,
	  underwater         = true,
      properties = {
        heat               = 60, 
        heatfalloff        = 1,
        maxheat            = 60, 
        pos                = [[0, 1, 0]],
        size               = 62, 
        sizegrowth         = 2.6, 
        speed              = [[0, 1.5, 0]],
        texture            = [[heatcloud]],
      },
	},
	dirt = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      properties = {
        airdrag            = 0.95,
        colormap           = [[0.04 0.03 0.02 0.05  0.4 0.3 0.2 0.5  0.04 0.03 0.02 0.05]],
        directional        = false,
        emitrot            = 85,
        emitrotspread      = 15,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.1, 0]],
        numparticles       = 48,
        particlelife       = 30,
        particlelifespread = 6,
        particlesize       = 18,
        particlesizespread = 7,
        particlespeed      = 6,
        particlespeedspread = 3,
        pos                = [[0, 0, 0]],
        sizegrowth         = 6,
        sizemod            = 0.75,
        texture            = [[dirt]],
    },
	},
	},
	--volcano2
   ["volcanoflash2"] = {
    groundflash = {
      circlealpha        = 1,
      circlegrowth       = 1.5,
      flashalpha         = 0.9,
      flashsize          = 60,
      ttl                = 35,
      color = {
        [1]  = 0.8,
        [2]  = 0.65,
        [3]  = 0.4,
      },
    },
	 mainhit = {
      air                = true,
      class              = [[heatcloud]],
      count              = 1,
      ground             = true,
      water              = true,
	  underwater         = true,
      properties = {
        heat               = 15, 
        heatfalloff        = 1,
        maxheat            = 15, 
        pos                = [[0, 1, 0]],
        size               = 42, 
        sizegrowth         = 2, 
        speed              = [[0, 1.5, 0]],
        texture            = [[heatcloud]],
      },
	},
	dirt = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      properties = {
        airdrag            = 0.95,
        colormap           = [[0.04 0.03 0.02 0.05  0.4 0.3 0.2 0.5  0.04 0.03 0.02 0.05]],
        directional        = false,
        emitrot            = 85,
        emitrotspread      = 15,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.1, 0]],
        numparticles       = 36,
        particlelife       = 28,
        particlelifespread = 6,
        particlesize       = 12,
        particlesizespread = 6,
        particlespeed      = 5,
        particlespeedspread = 3,
        pos                = [[0, 0, 0]],
        sizegrowth         = 3,
        sizemod            = 0.75,
        texture            = [[dirt]],
    },
	},
sphere = {
            air                = true,
            class              = [[CSpherePartSpawner]],
            count              = 1,
            ground             = true,
            water              = true,
			underwater         = true,
            properties = {
                alpha              = 0.5,
                alwaysvisible      = true,
                color              = [[0.8,0.65,0.4]],
                expansionspeed     = 6,
                ttl                = 45,
            },
        },	
	},
	--swatter
  ["swatterflash"] = {
    usedefaultexplosions = false,
  spark = {
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      unit               = 1,
	  water              = true,
      properties = {
        airdrag            = 0.97,
        colormap           = [[0.85 0.75 0.4 0.01   0.7 0.6 0.35 0.01   0.6 0.45 0.3 0.01   0 0 0 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 40,
        emitvector         = [[dir]],
        gravity            = [[0, -0.2, 0]],
        numparticles       = 8,
        particlelife       = 9,
        particlelifespread = 1,
        particlesize       = 9,
        particlesizespread = 2,
        particlespeed      = 3.5,
        particlespeedspread = 4,
        pos                = [[0, 1, 0]],
        sizegrowth         = 0,
        sizemod            = 1.0,
        texture            = [[simplespark]],
      },
    },
	 mainhit = {
      air                = true,
      class              = [[heatcloud]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        heat               = 24, --8
        heatfalloff        = 1,
        maxheat            = 24, --8
        pos                = [[0, 1, 0]],
        size               = 19.5, 
        sizegrowth         = 1, 
        speed              = [[0, 0.8, 0]],
        texture            = [[heatcloud]],
      },
	},
   },
   
   --stormcloud
   ["stormcloudflash"] = {
    groundflash = {
      circlealpha        = 1,
      circlegrowth       = 3,
      flashalpha         = 0.9,
      flashsize          = 46,
      ttl                = 24,
      color = {
        [1]  = 1,
        [2]  = 0.8,
        [3]  = 0.4,
      },
    },
	 mainhit = {
      air                = true,
      class              = [[heatcloud]],
      count              = 1,
      ground             = true,
      water              = true,
	  underwater         = true,
      properties = {
        heat               = 28, --8
        heatfalloff        = 1,
        maxheat            = 28, --8
        pos                = [[0, 1, 0]],
        size               = 32, 
        sizegrowth         = 1.3, 
        speed              = [[0, 1.5, 0]],
        texture            = [[heatcloud]],
      },
	},
	dirt = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      properties = {
        airdrag            = 0.95,
        colormap           = [[0.04 0.03 0.02 0.05  0.4 0.3 0.2 0.5  0.04 0.03 0.02 0.05]],
        directional        = false,
        emitrot            = 85,
        emitrotspread      = 5,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.1, 0]],
        numparticles       = 20,
        particlelife       = 20,
        particlelifespread = 5.5,
        particlesize       = 8,
        particlesizespread = 4.5,
        particlespeed      = 4,
        particlespeedspread = 1.5,
        pos                = [[0, 0, 0]],
        sizegrowth         = 6,
        sizemod            = 0.75,
        texture            = [[dirt]],
    },
	},
	speckdirt = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      properties = {
        airdrag            = 0.95,
        colormap           = [[0.02 0.015 0.01 0.075  0.2 0.15 0.1 0.75  0.02 0.015 0.01 0.075]],
        directional        = false,
        emitrot            = 25,
        emitrotspread      = 5,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.1, 0]],
        numparticles       = 4,
        particlelife       = 34,
        particlelifespread = 6,
        particlesize       = 3,
        particlesizespread = 3.5,
        particlespeed      = 3.75,
        particlespeedspread = 1.3,
        pos                = [[0, 0, 0]],
        sizegrowth         = 5,
        sizemod            = 1,
        texture            = [[randdots]],
    },
  },	
   },
   --geothermal
   ["geothermalflash"] = {
    groundflash = {
      circlealpha        = 1,
      circlegrowth       = 1.5,
      flashalpha         = 0.9,
      flashsize          = 75,
      ttl                = 36,
      color = {
        [1]  = 1,
        [2]  = 0.95,
        [3]  = 0.4,
      },
    },
	 mainhit = {
      air                = true,
      class              = [[heatcloud]],
      count              = 1,
      ground             = true,
      water              = true,
	  underwater         = true,
      properties = {
        heat               = 30, 
        heatfalloff        = 1,
        maxheat            = 30, 
        pos                = [[0, 1, 0]],
        size               = 46, 
        sizegrowth         = 2, 
        speed              = [[0, 1.5, 0]],
        texture            = [[heatcloud]],
      },
	},
	dirt = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      properties = {
        airdrag            = 0.95,
        colormap           = [[0.04 0.03 0.02 0.05  0.4 0.3 0.2 0.5  0.04 0.03 0.02 0.05]],
        directional        = false,
        emitrot            = 85,
        emitrotspread      = 15,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.1, 0]],
        numparticles       = 46,
        particlelife       = 28,
        particlelifespread = 5.5,
        particlesize       = 18,
        particlesizespread = 6,
        particlespeed      = 6,
        particlespeedspread = 3,
        pos                = [[0, 0, 0]],
        sizegrowth         = 6,
        sizemod            = 0.75,
        texture            = [[dirt]],
    },
	},
	sphere = {
            air                = true,
            class              = [[CSpherePartSpawner]],
            count              = 1,
            ground             = true,
            water              = true,
			underwater         = true,
            properties = {
                alpha              = 0.5,
                alwaysvisible      = true,
                color              = [[1,0.95,0.4]],
                expansionspeed     = 5.5,
                ttl                = 32,
            },
        },	
	},
	--Catapult
	["Catapultflash"] = {
    groundflash = {
      circlealpha        = 1,
      circlegrowth       = 3,
      flashalpha         = 0.9,
      flashsize          = 46,
      ttl                = 24,
      color = {
        [1]  = 1,
        [2]  = 0.8,
        [3]  = 0.4,
      },
    },
	 mainhit = {
      air                = true,
      class              = [[heatcloud]],
      count              = 1,
      ground             = true,
      water              = true,
	  underwater         = true,
      properties = {
        heat               = 22, --8
        heatfalloff        = 1,
        maxheat            = 26, --8
        pos                = [[0, 1, 0]],
        size               = 33, 
        sizegrowth         = 1.3, 
        speed              = [[0, 1.5, 0]],
        texture            = [[heatcloud]],
      },
	},
	dirt = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      properties = {
        airdrag            = 0.95,
        colormap           = [[0.04 0.03 0.02 0.05  0.4 0.3 0.2 0.5  0.04 0.03 0.02 0.05]],
        directional        = false,
        emitrot            = 85,
        emitrotspread      = 5,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.1, 0]],
        numparticles       = 24,
        particlelife       = 24,
        particlelifespread = 6,
        particlesize       = 9,
        particlesizespread = 4.5,
        particlespeed      = 4,
        particlespeedspread = 2,
        pos                = [[0, 0, 0]],
        sizegrowth         = 6,
        sizemod            = 0.75,
        texture            = [[dirt]],
    },
	},
	speckdirt = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      properties = {
        airdrag            = 0.95,
        colormap           = [[0.02 0.015 0.01 0.075  0.2 0.15 0.1 0.75  0.02 0.015 0.01 0.075]],
        directional        = false,
        emitrot            = 25,
        emitrotspread      = 5,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.1, 0]],
        numparticles       = 6,
        particlelife       = 36,
        particlelifespread = 7,
        particlesize       = 3,
        particlesizespread = 1.5,
        particlespeed      = 4,
        particlespeedspread = 1.5,
        pos                = [[0, 0, 0]],
        sizegrowth         = 5,
        sizemod            = 1,
        texture            = [[randdots]],
    },
  },	
   },
      --alpha
	["alphaflash"] = {
	usedefaultexplosions = false,
	underwater        = true,
    groundflash = {
      circlealpha        = 1,
      circlegrowth       = 4,
      flashalpha         = 0.9,
      flashsize          = 180,
      ttl                = 35,
      color = {
        [1]  = 0,
        [2]  = 0.6,
        [3]  = 0.6,
      },
    },
	Mainhit = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      underwater        = true,
      properties = {
        airdrag            = 0.95,
        colormap           = [[0 0.6 0.6 1  0 0.6 0.6 0.8  0 0.6 0.6 0.0]],
        directional        = false,
        emitrot            = 0,
        emitrotspread      = 0,
        emitvector         = [[0, 0, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 1,
        particlelife       = 36,
        particlelifespread = 0,
        particlesize       = 8,
        particlesizespread = 0,
        particlespeed      = 0,
        particlespeedspread = 0,
        pos                = [[0, 0, 0]],
        sizegrowth         = 2.5,
        sizemod            = 1,
        texture            = [[flare]],
    },
	},
	dirt = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      underwater        = true,
      properties = {
        airdrag            = 0.95,
        colormap           = [[0.04 0.03 0.02 0.05  0.4 0.3 0.2 0.5  0.04 0.03 0.02 0.05]],
        directional        = false,
        emitrot            = 85,
        emitrotspread      = 5,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.1, 0]],
        numparticles       = 15,
        particlelife       = 20,
        particlelifespread = 8,
        particlesize       = 5,
        particlesizespread = 4,
        particlespeed      = 3.5,
        particlespeedspread = 1.2,
        pos                = [[0, 0, 0]],
        sizegrowth         = 4,
        sizemod            = 0.75,
        texture            = [[dirt]],
    },
	},
	speckdirt = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      underwater        = true,
      properties = {
        airdrag            = 0.95,
        colormap           = [[0.02 0.015 0.01 0.075  0.2 0.15 0.1 0.75  0.02 0.015 0.01 0.075]],
        directional        = false,
        emitrot            = 25,
        emitrotspread      = 5,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.1, 0]],
        numparticles       = 5,
        particlelife       = 30,
        particlelifespread = 8,
        particlesize       = 4.5,
        particlesizespread = 3.2,
        particlespeed      = 3,
        particlespeedspread = 1,
        pos                = [[0, 0, 0]],
        sizegrowth         = 4,
        sizemod            = 0.75,
        texture            = [[randdots]],
    },
  },
  sphere = {
            air                = true,
            class              = [[CSpherePartSpawner]],
            count              = 1,
            ground             = true,
            water              = true,
			underwater         = true,
            properties = {
                alpha              = 0.5,
                alwaysvisible      = true,
                color              = [[0,0.6,0.6]],
                expansionspeed     = 5,
                ttl                = 35,
            },
        },	
   },

	["alphaburstflash"] = {
	usedefaultexplosions = false,
	underwater        = true,
    groundflash = {
      circlealpha        = 1,
      circlegrowth       = 4,
      flashalpha         = 0.9,
      flashsize          = 200,
      ttl                = 37,
      color = {
        [1]  = 0,
        [2]  = 0.5,
        [3]  = 0.75,
      },
    },
	Mainhit = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      underwater        = true,
      properties = {
        airdrag            = 0.95,
        colormap           = [[0 0.5 0.75 1  0 0.5 0.4 0.8  0 0.6 0.6 0.0]],
        directional        = false,
        emitrot            = 0,
        emitrotspread      = 0,
        emitvector         = [[0, 0, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 1,
        particlelife       = 38,
        particlelifespread = 0,
        particlesize       = 8,
        particlesizespread = 0,
        particlespeed      = 0,
        particlespeedspread = 0,
        pos                = [[0, 0, 0]],
        sizegrowth         = 2.5,
        sizemod            = 1,
        texture            = [[flare]],
    },
	},
	dirt = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      underwater        = true,
      properties = {
        airdrag            = 0.95,
        colormap           = [[0.04 0.03 0.02 0.05  0.4 0.3 0.2 0.5  0.04 0.03 0.02 0.05]],
        directional        = false,
        emitrot            = 85,
        emitrotspread      = 5,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.1, 0]],
        numparticles       = 15,
        particlelife       = 20,
        particlelifespread = 8,
        particlesize       = 5,
        particlesizespread = 4,
        particlespeed      = 3.5,
        particlespeedspread = 1.25,
        pos                = [[0, 0, 0]],
        sizegrowth         = 4,
        sizemod            = 0.75,
        texture            = [[dirt]],
    },
	},
	speckdirt = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      underwater        = true,
      properties = {
        airdrag            = 0.95,
        colormap           = [[0.02 0.015 0.01 0.075  0.2 0.15 0.1 0.75  0.02 0.015 0.01 0.075]],
        directional        = false,
        emitrot            = 25,
        emitrotspread      = 5,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.1, 0]],
        numparticles       = 5,
        particlelife       = 30,
        particlelifespread = 8,
        particlesize       = 4.5,
        particlesizespread = 3.25,
        particlespeed      = 3,
        particlespeedspread = 1,
        pos                = [[0, 0, 0]],
        sizegrowth         = 4,
        sizemod            = 0.75,
        texture            = [[randdots]],
    },
  },
  sphere = {
            air                = true,
            class              = [[CSpherePartSpawner]],
            count              = 1,
            ground             = true,
            water              = true,
			underwater         = true,
            properties = {
                alpha              = 0.5,
                alwaysvisible      = true,
                color              = [[0,0.6,0.6]],
                expansionspeed     = 5.1,
                ttl                = 38,
            },
        },	
   },
}
