return lowerkeys({
  alpha_dead = {
            description = "dead alpha :(",
            damage = 7325,
            object = "dead/AlphaDED.s3o",
            footprintz = 4,
            footprintx = 4,
            smokeTime = 400,
            reclaimable = true,
            reclaimTime = 4888,
            metal = 4888,
            hitdensity = 150,
			featureDead  = "alpha_heap",
            world = "All Worlds",
            category = "dedunit",
			collisionvolumeoffsets = "0 -5 0",
			collisionVolumeScales     =  "57 74 90",
			collisionvolumetype = "box",
},
alpha_heap = {
            description = "very dead alpha :(",
            damage = 1465,
            object = "dead/Pieces_Big.s3o",
            footprintz = 4,
            footprintx = 4,
            smokeTime = 100,
            reclaimable = true,
			blocking = false,
            reclaimTime = 1222,
            metal = 1222,
            hitdensity = 150,
            world = "All Worlds",
            category = "dedunit",
			collisionvolumeoffsets = "0 0 0",
			collisionvolumescales = "60 8 60",
			collisionvolumetype = "box",
},
})
