return lowerkeys({
  cutlass_dead = {
            description = "dead cutlass :(",
            damage = 335,
            object = "dead/CutlassDED.s3o",
            footprintz = 3,
            footprintx = 3,
            smokeTime = 400,
            reclaimable = true,
            reclaimTime = 86,
            metal = 86,
            hitdensity = 150,
			featureDead  = "cleaver_heap",
            world = "All Worlds",
            category = "dedunit",
			collisionvolumeoffsets = "0 -5 0",
			collisionVolumeScales =  "31 32 43",
			collisionvolumetype = "box",
},
cutlass_heap = {
            description = "very dead cutlass :(",
            damage = 67,
            object = "dead/Pieces_Big.s3o",
            footprintz = 3,
            footprintx = 3,
            smokeTime = 100,
            reclaimable = true,
			blocking = false,
            reclaimTime = 21.5,
            metal = 21.5,
            hitdensity = 150,
            world = "All Worlds",
            category = "dedunit",
			collisionvolumeoffsets = "0 0 0",
			collisionvolumescales = "45 7 45",
			collisionvolumetype = "box",
},
})
