return lowerkeys({
 volcano_dead = {
            description = "dead Volcano :(",
            damage = 3500,
            object = "dead/volcanoDED.s3o",
            footprintz = 12,
            footprintx = 12,
            smokeTime = 8000,
            reclaimable = true,
            reclaimTime = 8000,
            metal = 8000,
            hitdensity = 100,
            world = "All Worlds",
            category = "dedunit",
			featureDead = "volcano_heap",
			collisionVolumeOffsets    =  "0 25 0",
			collisionVolumeScales     =  "140 276 140",
			collisionvolumetype = "box",
},
volcano_heap = {
            description = "very dead Volcano :(",
            damage = 700,
            object = "dead/Pieces_BB.s3o",
            footprintz = 12,
            footprintx = 12,
            smokeTime = 2000,
            reclaimable = true,
			blocking = false,
            reclaimTime = 2000,
            metal = 2000,
            hitdensity = 150,
            world = "All Worlds",
            category = "dedunit",
			collisionvolumeoffsets = "0 0 0",
			collisionvolumescales = "150 15 150",
			collisionvolumetype = "box",
},
})
