return lowerkeys({
  windturbine_dead = {
            description = "dead wind turbine :(",
            damage = 112.5,
            object = "dead/Wind TurbineDED.s3o",
            footprintz = 3,
            footprintx = 3,
            smokeTime = 400,
            reclaimable = true,
            reclaimTime = 22,
            metal = 22,
            hitdensity = 100,
            world = "All Worlds",
            category = "dedunit",
			featureDead = "llt_heap",
			collisionVolumeOffsets    =  "0 25 0",
			collisionVolumeScales     =  "28 80 24",
			collisionvolumetype = "box",
},
windturbine_dead = {
            description = "very dead wind turbine :(",
            damage = 22.5,
            object = "dead/Pieces_Small.s3o",
            footprintz = 2,
            footprintx = 2,
            smokeTime = 100,
            reclaimable = true,
			blocking = false,
            reclaimTime = 5.5,
            metal = 5.5,
            hitdensity = 100,
            world = "All Worlds",
            category = "dedunit",
			collisionvolumeoffsets = "0 0 0",
			collisionvolumescales = "35 5 35",
			collisionvolumetype = "box",
},
})
